namespace Sprint_0.Scripts.Enemy
{
    public enum EnemyType
    {
        Stalfos,
        Goriya,
        Keese,
        Gel,
        Zol,
        Spiketrap,
        Wallmaster,
        Aquamentus,
        Rope,
        Dodongo,
        OldMan,
        Merchant,
        Bubble,
        Darknut,
        Patra,
        PatraMinion,
        MegaStalfos,
        MegaGel,
        MegaZol,
        MegaKeese,
        MegaDarknut,
        Manhandla,
        ManhandlaHead
    }
}
